### ISSUE TITLE
Unable to save template [0.3a-PLUS]

### ISSUE THREAD

**Issue by OblivionPrime** [Novynn/acquisitionplus#1]
Steps to re-produce:
- Fresh install with version 0.3a-PLUS.
- Add new thread ID
- Click "edit template"
- Notice template is blank
- Add template information
- Click ok
- Click "edit template" again
- Template is still empty 

Workaround:
- Install 0.3-PLUS.
- Setup template
- Update to 0.3a-PLUS.
- Template now saves

**Comment by Novynn** [comment]
Hi, thanks for the report. I'll check this out.
