### ISSUE TITLE
Not updating shops (linux)

### ISSUE THREAD

**Issue by ccomly** [Novynn/acquisitionplus#10]
RROR 2015-10-04T14:54:18.901 An error occurred with shop 1440599: Timed out while submitting to the server. 

hasnt updated yet from the old acqusition

**Comment by ccomly** [comment]
trying max timeout
nope still not updating :/

**Comment by Novynn** [comment]
You may have too many items for the shop to be posted (this is on GGG's end, as they have to verify each item server-side). There's really not much I can do about it unfortunately.

**Comment by ccomly** [comment]
but it works fine in vanilla acqusition?

**Comment by Novynn** [comment]
I'm sorry, this is on GGG's end. You can try to play around with the template options to get it to work.
