### ISSUE TITLE
Doesn't load Name of Tab 2

### ISSUE THREAD

**Issue by TehDarkAbyss** [Novynn/acquisitionplus#12]
![screenshot_2](https://cloud.githubusercontent.com/assets/1341362/10414337/64330f1a-6f84-11e5-8f5f-3f4f406ac2d6.png)

**Comment by TehDarkAbyss** [comment]
The Items in Tab A are correct, the items in Tab C are actually the items in Tab B, and the items in Tab D are actually the items in Tab C. It also loads one less Tab than the real number of tabs. If I exclude all tabs except Tab A-D it only Loads Tab A, C, and D. Showing the items in Tab A, B, and C.

**Comment by Novynn** [comment]
Is Tab B in your exclusion list? If so then this is the same problem as #11 which has been fixed for the next release by c2da68cc07bd780e3bdcc8dcbe69b8c88b0e2556.

**Comment by TehDarkAbyss** [comment]
My Exclusion list includes Tab names 1-100, T1-T15, and Alt Code 255. I don't feel like Tab B would be included in any of those.

**Comment by Novynn** [comment]
Very strange. I'll do a release with the fix and hopefully it fixes your problem.

**Comment by Novynn** [comment]
0.3d is released with a fix for the Exclusion feature. Do you still have the issue with your tabs?

**Comment by Novynn** [comment]
Closing.
