### ISSUE TITLE
Shop code to long

### ISSUE THREAD

**Issue by verisar** [Novynn/acquisitionplus#16]
I have four different shops basically all for my stash and with regular acquisition it would split it up, but with + it seems to be trying to update all four shops with the same info which is 168234 items which isnt going to work.

**Comment by Novynn** [comment]
Acquisition Plus doesn't split up your items between your shops, instead it has a templating system.

Would definitely be a nice feature to have though!

**Comment by verisar** [comment]
Seems weird that it wouldnt cause when i think of a base with additions i think of the original plus some.

**Comment by Novynn** [comment]
Should be fixed by 7575b5bf15fad707619205bd2233ae8082d77a1c
