### ISSUE TITLE
Shop templates; items in wrong positions and redundant text (spoilers) are not cleaned up .

### ISSUE THREAD

**Issue by Illviljan** [Novynn/acquisitionplus#20]
It seems like the shop template isn't working correctly at the moment. My complete template gives the over 50000 characters error, which lead me to believe it doesn't clean up the redundant spoilers. However with a much smaller shop template I found a few other issues as well. In this tested example I have put
- 1 item in the "1c" tab 
- 0 item in the "2c" tab
- 1 item in the "3c" tab

and I'm using the following shop template:
# Shop Template

Welcome to my shop! (Last Updated {LastUpdated}),

Best way to contact me is to send a whisper in-game with the [b]FULL NAME[/b] of the item and [b]THE LISTED BUYOUT[/b].  You can also send me a forum PM if I'm not online in game.  Don't post in this thread, I don't check it regularly. 
My IGN is {IGN}.
Timezone: GMT +1

[spoiler="~b/o 1 chaos"]
{Stash:1c|include.ignored}
[/spoiler]

[spoiler="~b/o 2 chaos"]
{Stash:2c|include.ignored}
[/spoiler]

[spoiler="~b/o 3 chaos"]
{Stash:3c|include.ignored}
[/spoiler]

---

In earlier versions this would have resulted in:
- 1 item being displayed in the 1 chaos spoiler.
- The 2 chaos spoiler would have been removed since there is no item in it.
- 1 item being displayed in the 3 chaos spoiler, 

However, this is the result:
# Shop Preview

Welcome to my shop! (Last Updated december 12, 2015 02:41 ),

Best way to contact me is to send a whisper in-game with the [b]FULL NAME[/b] of the item and [b]THE LISTED BUYOUT[/b].  You can also send me a forum PM if I'm not online in game.  Don't post in this thread, I don't check iServana_Hallt regularly. 
My IGN is .
Timezon[linkItem location="Stash5" league="Hardcore Talisman" x="0" y="0"]e: GMT +1
[linkItem location="Stash7" league="Hardcore Talisman" x="0" y="0"]
[spoiler="~b/o 1 chaos"]

[/spoiler]

[spoiler="~b/o 2 chaos"]

[/spoiler]

[spoiler="~b/o 3 chaos"]

[/spoiler]

---

From the shop preview we can see that the 2 items are not in the correct places for some reason and since there is no item in the 2 chaos tab that spoiler should have been removed but it was not. 

I'm not really sure what's going on here, my template worked great on previous versions(0.3e) so the issue came with the Talisman update.

**Comment by Novynn** [comment]
Yeah, something is definitely messed up there.

**Comment by Novynn** [comment]
0d35b1ab1742e3495cbd04b0cc0dcec17031016b has fixed the template offsets being wrong.

As for the empty spoiler tags etc, this is now intended design to reduce load on the template engine. Instead of doing:

```
[spoiler="~b/o 1 chaos"]
{Stash:1c|include.ignored}
[/spoiler]
```

you can instead use:

```
{Stash:1c|include.ignored|wrap|header:~b/o 1 chaos}
```

which will correctly wrap stashes in spoiler tags while also removing empty sections if it comes across them.

**Comment by Illviljan** [comment]
Great work! 
Seems to be working fine, one final thing I'd like to mention is that each row of: 
_{Stash:1c|include.ignored|wrap|header:~b/o 1 chaos}_
Is still left in the shop preview, since my template has like 3k rows of these this means there's 3k of empty rows in the shop thread... RIP character efficiency.

I solved this minor issue by not creating a new row for each {stash:} like this:
_{Stash:1c|include.ignored|wrap|header:~b/o 1 chaos}{Stash:2c|include.ignored|wrap|header:~b/o 2_ _chaos}{Stash:3c|include.ignored|wrap|header:~b/o 3 chaos} ..._

**Comment by Novynn** [comment]
Yeah when I tried to make it eat the newline as well it started eating the next _two_ new lines. It'll be something I'll be looking to fix in the future for sure.
