### ISSUE TITLE
can't compile on linux

### ISSUE THREAD

**Issue by muzzol** [Novynn/acquisitionplus#22]
Output when trying to compile:

```
src/mainwindow.cpp: In member function ‘void MainWindow::LoadSearches()’:
src/mainwindow.cpp:830:31: error: ‘class QJsonObject’ has no member named ‘toVariantHash’
         search->LoadState(obj.toVariantHash());
                               ^
src/mainwindow.cpp: In member function ‘void MainWindow::SaveSearches()’:
src/mainwindow.cpp:843:22: error: ‘fromVariantHash’ is not a member of ‘QJsonObject’
         array.append(QJsonObject::fromVariantHash(hash));
                      ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-inconsistent-missing-override"
Makefile:958: recipe for target 'mainwindow.o' failed
make: *** [mainwindow.o] Error 1
```

**Comment by Novynn** [comment]
Acquisition Plus requires Qt 5.5 to compile. I should probably put that in the readme somewhere...

**Comment by muzzol** [comment]
I see. Which packages do I need on a Debian based distro to compile it?

**Comment by Novynn** [comment]
I use a Qt 5.5 repo I found:

> sudo add-apt-repository -y ppa:beineri/opt-qt55
> sudo apt-get install qt55base qt55webkit

Webkit is only required if you're compiling the Steam version.

EDIT: The install-travis-deps.sh file has everything needed, since that's what the linux text build uses.

**Comment by muzzol** [comment]
that did the trick
    add-apt-repository ppa:beineri/opt-qt551-trusty
    apt-get install qt55base

then to compile
    /opt/qt55/bin/qmake && make

I'm testing it now to see if I face any problems.

and yes, it would be useful some kind of note about required packages/versions to compile. can't that check be done inside qtcreator project?

**Comment by Novynn** [comment]
Yes this could be done, it might just be easier to use a `QVariantMap` (with `QJsonObject::fromVariantMap`) which just requires Qt 5. This would cover more cases I'm sure.

**Comment by muzzol** [comment]
I can see next Ubuntu releas will ship 5.5, but it's always a good idea use more common methods for better compatibility.

thx for your time. works great on a ubuntu trusty machine
