### ISSUE TITLE
An error occurred with shop #: The forum responded with an error: Failed to find item.

### ISSUE THREAD

**Issue by Zoxjib** [Novynn/acquisitionplus#25]
This probably happened after moving an item around in the stash.

The problem with this message is that you have no idea which item is causing the problem, the log gives you no information.

**Comment by Novynn** [comment]
I think this is all the information that is provided by GGG on the issue, so there's not much I can do about the message.

You can always just force the stash to update again with the controls in the bottom-right which will fix the problem though.
