### ISSUE TITLE
Sell items that are equiped by character?

### ISSUE THREAD

**Issue by IceLancerSR** [Novynn/acquisitionplus#32]
Currently it is not possible to list items that are equiped on some of characters.
Can this be changed? 
I don't want to keep everything in my 4 stash tab just to sell it.Some of my toons are wearing stuff, but that items do not get listed on trade even if i put price

**Comment by Novynn** [comment]
Open your shop template and add: `include.character` before the ending brace. It should end up looking something like `{everything|group|include.character}`.

**Comment by IceLancerSR** [comment]
Thank you
