### ISSUE TITLE
Excluded tab seemingly randomly shows up and posts items

### ISSUE THREAD

**Issue by omegaweapon1** [Novynn/acquisitionplus#38]
I have it so it excludes all tabs named 'x' and my first tabs are 'x' where I throw all the items in while mapping, occasionaly (not always) the first tab will show up in acquisition as tab #0 labelled as "1" or "0" and acquisition will post items from that tab that have buyouts.  Is there a way to prevent this from happening, if so how would I go about it, thank you for your time.

**Comment by Novynn** [comment]
Hmm, I was actually wondering if this would show up. It seems your last active tab will be received first and will bypass the filter.

I'll get this fixed ASAP.

**Comment by omegaweapon1** [comment]
If this is fixable and isn't too much trouble I would greatly appreciate it, I switched to Acquisition plus at the first release and never went back.  Thank you again for your hard work :3

**Comment by omegaweapon1** [comment]
I'm new to this stuff, how do I go about downloading the fix if it has been fixed? just redownload the latest release? or something else?
