### ISSUE TITLE
Fork status?

### ISSUE THREAD

**Issue by krab** [Novynn/acquisitionplus#42]
What happens with fork? Not supported anymore? Also what is https://github.com/Novynn/Adamant

**Comment by CapitalF** [comment]
Project seems dead to me. It's now two releases behind Acquisition and my listings are constantly getting corrupted.

**Comment by Novynn** [comment]
Yeah sorry, I've had lots of stuff on my plate! I'll look into updating it with the latest Acquisition stuff.

**Comment by Novynn** [comment]
Adamant is the replacement for Acquisition/Plus that I've been working on. It aims to do different things, so it's a completely new project.

**Comment by Novynn** [comment]
Latest Acquisition code has been merged, some features were discarded...
