### ISSUE TITLE
3218 spaces in template preview

### ISSUE THREAD

**Issue by CapitalF** [Novynn/acquisitionplus#46]
I suspect that template generation needs to be reviewed. The second page of my template previews has 3218 spaces in between the "Shop made with Acquisition Plus" header and the first item listing.

**Comment by Novynn** [comment]
Could you link your problematic template here please? Cheers.

**Comment by CapitalF** [comment]
[tab2.txt](https://github.com/Novynn/acquisitionplus/files/191302/tab2.txt)

Tab 2/4. 3-4 are empty.

**Comment by Novynn** [comment]
Ah, I mean your template not the preview.

**Comment by CapitalF** [comment]
I x-ed out the thread IDs:

```

https://www.pathofexile.com/forum/view-thread/xxxxxxx
https://www.pathofexile.com/forum/view-thread/xxxxxxx
https://www.pathofexile.com/forum/view-thread/xxxxxxx
https://www.pathofexile.com/forum/view-thread/xxxxxxx

{everything|group}

[url=https://github.com/Novynn/acquisitionplus/releases]Shop made with Acquisition Plus[/url]
```
