### ISSUE TITLE
Acquisition Plus isn't detecting the x64 version, can't be seen as online.

### ISSUE THREAD

**Issue by Illviljan** [Novynn/acquisitionplus#47]
Similar issue at: https://github.com/xyzz/acquisition/issues/362

**Comment by Novynn** [comment]
12b414e97035becaef26c0801353f48e477121b1

**Comment by Tomeqf** [comment]
While waiting for devs to update acquisition to detect PathofExile_64x.exe task (Dx11 version), just open DX9 version of PoE and leave it in login menu, mute, minimize, and go play on Dx11 version. Leaving D9 version in login menu is enough for acquisition to update status, as it simply searches for Pathofexile.exe task being run.
