### ISSUE TITLE
compiling issue arch linux 64bit

### ISSUE THREAD

**Issue by ccomly** [Novynn/acquisitionplus#5]
its really weird cause the file is there, poking around to find the issue currently

$ make
g++ -c -pipe -Wno-inconsistent-missing-override -Wno-missing-field-initializers -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ideps/QsLog -Isrc -Ideps -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o mainwindow.o src/mainwindow.cpp
In file included from src/mainwindow.cpp:21:0:
./ui_mainwindow.h:32:32: fatal error: forms\currencypane.h: No such file or directory
compilation terminated.
Makefile:1104: recipe for target 'mainwindow.o' failed
make: **\* [mainwindow.o] Error 1

**Comment by ccomly** [comment]
well duh, 
forms\currencypane.h
forms/currencypane.h

and related

**Comment by ccomly** [comment]
well its coredumping now shortly after login with sessionid. cant really do much more, im too noob for gdb. this is as far as i got

[New Thread 0x7fffce0a3700 (LWP 32282)]
[New Thread 0x7fffcd8a2700 (LWP 32283)]

Program received signal SIGSEGV, Segmentation fault.
0x0000555555686eab in CurrencyPane::UpdateGraph(QMap<double, double>) ()

**Comment by ccomly** [comment]
ehm recompiled with debug enabled i think?

$ ./acquisitionplus 
 INFO 2015-09-27T20:55:15.198 -------------------------------------------------------------------------------- 
 INFO 2015-09-27T20:55:15.198 Built with Qt 5.5.0 running on 5.5.0 
 INFO 2015-09-27T20:55:19.605 Logged in as: "xxxxxx" 
 INFO 2015-09-27T20:55:19.643 Updating stash tabs 
ASSERT: "!isEmpty()" in file /usr/include/qt/QtCore/qmap.h, line 397
Aborted (core dumped)

**Comment by ccomly** [comment]
ops messed up there i think

**Comment by Novynn** [comment]
Let me know how far you get now! I'll have to set up a linux distro for the future

**Comment by ccomly** [comment]
well its starts up fine and seems to work, its complaining about shops tho.

ERROR 2015-09-28T20:20:03.091 An error occurred with shop xxxxxxxx: The forum responded with an error: blablabla is more than 50000 characters long.

 i have added both my shops, and works in vanilla acqusition. idk whats going on here.

**Comment by Novynn** [comment]
Acquisition Plus uses a different system than Acquisition for shops. You may have to play around with the template a little to get it to suit your needs. There are various options that you can add, there's details about it on the release page.

By the sounds of it, you might need 3 shop threads instead of two (to avoid going over the character limit).
